### ISSUE TITLE
(noob q): unable to install 

### ISSUE THREAD

**Issue by rushikb** [maraujo/pySocialWatcher#20]
Apologies if this is a very basic question, but I'm still learning my ropes with Python, and wanted to use this project. I carried out the installation instructions, and then initiated jupyter lab running a python 2 kernel to run the code. However, when I try to run watcherAPI, I keep running into the same error- "No Module named main". Any help would be greatly appreciated, I haven't been able to find any tutorial notebooks either, but I'm happy to write one once I'm able to do this.

<img width="788" alt="screenshot" src="https://user-images.githubusercontent.com/6484525/52032731-31406200-255d-11e9-9d2e-4682d18467b1.png">

**Comment by sibeleker** [comment]
I see that you closed this issue but could you tell me the solution you found? I have the same problem.

**Comment by maraujo** [comment]
Hi Sibeleker,
Your python is not finding the main.py module. It is an strange error since main.py is in the repo. 
Did you followed the installation and tried to run the section Quick Start?

**Comment by soongy** [comment]
Hi there, I'm having this problem as well!

**Comment by sibeleker** [comment]
Hi soongy! I managed to solve the problem but don't remember how exactly. I use Python 2.7, and I work on a development env instead of notebooks. My code is below:

```
from pysocialwatcher import watcherAPI, constants 
if __name__ == '__main__':
    watcher = watcherAPI()
    watcher.add_token_and_account_number(token, account)  
    #watcher.check_tokens_account_valid()
    input_file = "....json"
    #input_data_json = watcher.read_json_file(input_file)
    #watcher.expand_input_if_requested(input_data_json)
    #watcher.check_input_integrity(input_data_json)
    watcher.run_data_collection(input_file)
```

**Comment by tovaperlman** [comment]
Hi, we are attempting to do this install now and getting the same error that we can't import main. We are now working on Python 3.8. Any solutions on what to do?
