### ISSUE TITLE
MINOR ISSUE: Innacurate documentation of SLEEP constant

### ISSUE THREAD

**Issue by julianface** [maraujo/pySocialWatcher#8]
Hey I was trying to fiddle with the SLEEP constant as per the documentation below:

"Advaced Configurations
#####Change Sleep time between requests to 10s:

from pysocialwatcher import constants
constants.SLEEP = 10"

but the correct constant seems to be 'SLEEP_TIME' rather than 'SLEEP'

Best,

Julian

**Comment by maraujo** [comment]
Thank you for showing this error. I'll update the documentation.
